### ISSUE TITLE
"AND logic" not working

### ISSUE THREAD

**Issue by hsakareem** [cjbarrie/academictwitteR#102]
Hi,
I tried the "OR logic" multiple times. Never encountered any issue. However, I tried the "AND logic" recently, and it is not working. I used the following command:

df <- get_all_tweets("mhealth AND children", "2021-01-05T00:00:00z", "2021-06-06T00:00:00z", lang = "en", bearer_token)

Note: The "OR logic" is working fine in the above command.

**Comment by justinchuntingho** [comment]
For Twitter v2 API, there is no AND operator. You can simply use a space between search terms ("mhealth children") and it will act as an AND logic.

**Comment by hsakareem** [comment]
@justinchuntingho, Thanks. It worked.
