### ISSUE TITLE
Time wasting `Sys.sleep` in `fetch_data`

### ISSUE THREAD

**Issue by chainsawriot** [cjbarrie/academictwitteR#119]
**Is your feature request related to a problem? Please describe.**

I think this [Sys.sleep](https://github.com/cjbarrie/academictwitteR/blob/13e12930100f8141c206480c63e25e4145d7c361/R/utils.R#L113) in `fetch_data` is quite useless: there is no possible race condition to wait there, especially when there is only one page of data to retrieve. 

**Describe the solution you'd like**

If the intention is to wait a bit before the page change, a better solution is to move this `Sys.sleep` after the two `if` statements, i.e. after line 124, the very last line in the `while` loop.

**Comment by justinchuntingho** [comment]
Yup, you are right, as long as we can catch rate-limit error (and sleep and retry), we don't need to wait between pages.

**Comment by chainsawriot** [comment]
@justinchuntingho ok, I am going to axe this, because a large chunk of my (testing) time is wasted in this `Sys.sleep`.
