### ISSUE TITLE
Doc: `bind_tweet_jsons` has been mistyped twice in the code

### ISSUE THREAD

**Issue by chainsawriot** [cjbarrie/academictwitteR#122]
**Describe the bug**

`bind_tweet_jsons` has been mistyped as `bind_tweets_json` [twice in the output](https://github.com/cjbarrie/academictwitteR/search?q=bind_tweets_json). It may hint at the cognitive load needed to remember this function name (where should I put the "s"?).

**Comment by cjbarrie** [comment]
You're right. And, in truth, there is no need to have two functions `bind_tweet_jsons()` and `bind_user_jsons()`. 

One function e.g. called `bind_tweets`, with an argument specifying if user wants to bind data_* or users_* JSON files. This would also be more consistent with the `bind_tweets` argument in the `get_all_tweets()` function
