### ISSUE TITLE
Error in if (httr::headers(r)$`x-rate-limit-remaining` == "1") { :    argument is of length zero

### ISSUE THREAD

**Issue by mkalz** [cjbarrie/academictwitteR#13]
**Describe the bug**
I was trying to build an archive for a huge amount of tweets for two hashtags (ca. 700 000) from 2013 onwards and I ran first against memory problems (Ubuntu 18.04. R-Studio-Server Droplet on Digitalocean). After checking the memory during the construction of the RDS-file I saw that I need to increase the memory. Running the same query with double memory (2 GB) led to the same problem. Now I tried to only query for one hashtag (ca. 300 000 tweets) and the memory seems to be ok. But now I get the following error message:

`Error in if (httr::headers(r)$`x-rate-limit-remaining` == "1") { : argument is of length zero`

**Expected behavior**
Produce an .RDS file.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Safari
 - Version 14.0.3

**Comment by justinchuntingho** [comment]
Thanks for reporting. The current version stores the entire dataset within memory when collecting/parsing and it will hit memory limits sooner or later. I think the best bet for now would be to split up the query (eg using date range).

In the long run, it could be useful to have an option to batch process the data in smaller chunks.

**Comment by mkalz** [comment]
Thanks @justinchuntingho This is exactly what I did.
