### ISSUE TITLE
get_all_tweets error code 503

### ISSUE THREAD

**Issue by tiangenglu** [cjbarrie/academictwitteR#135]
Hey all,
I downloaded the package on May 14 (3 days after its official release). The package worked well at the beginning (before May 20) when I downloaded all tweets with a hashtag (N = 24009) between 2011 and 2012. Later, when I was working on another download (possibly with a much larger number of tweets, say, 100k), the get_all_tweets stopped working.

**Describe the bug**
The "get_all_tweets" command works sporadically, especially when the actual number of tweets is large (e.g. larger than several thousand). "get_all_tweets" don't work 99% of the time when I try to use the 'build_query' command.

The following:
CODE:
S281_early <- get_all_tweets(query = build_query("#s281",is_retweet = FALSE, lang = "en"),start_tweets = "2017-02-02T00:47:43.000Z", end_tweets = "2018-09-18T00:47:43.000Z", bearer_token = bearer.token, bind_tweets = TRUE)

ERROR MESSAGE:
Recommended to specify a data path in order to mitigate data loss when ingesting large amounts of data.Tweets will not be stored as JSONs or as a .rds file and will only be available in local memory if assigned to an object.query: <#s281 -is:retweet lang:en>: (tweets captured this page: 489). Total pages queried: 1. Total tweets ingested: 489. 
Error in get_tweets(q = built_query, n = 500, start_time = start_tweets,  : 
  something went wrong. Status code: 503

**To Reproduce**
This is the code I have

Tweets <- get_all_tweets(query = build_query("#s281",is_retweet = FALSE, lang = "en"),start_tweets = "2017-02-02T00:47:43.000Z", end_tweets = "2018-09-18T00:47:43.000Z", bearer_token = bearer.token, bind_tweets = TRUE)

**Screenshots**
![image](https://user-images.githubusercontent.com/58899759/121796349-483ff600-cbe6-11eb-847d-91f5fdf15862.png)
**Desktop (please complete the following information):**
 - IOS

This is an amazing package. Thank you in advance for your time in working on this issue.

**Comment by cjbarrie** [comment]
Hey! Thanks for using our package.

Status code 503 is when Twitter is receiving demands over capacity. There is ongoing discussion around this on the developer boards. But this is a an issue on the client side (Twitter). 

At present we are incorporating better error handling to try to tackle this

**Comment by psalmuel19** [comment]
Hi, 
I also just encountered same error with the code: 
Error in get_tweets(q = built_query, n = 500, start_time = start_tweets,  : 
  something went wrong. Status code: 503
Is there any update on it from the client?

**Comment by igorbrigadir** [comment]
We had the same problem in twarc - the solution is to set the `max_results` parameter to 100 instead of 500 when requesting context annotations, as this is a new API limit - only a max of 100 tweets can only be returned when requesting this expansion https://github.com/DocNow/twarc/issues/449 and https://twittercommunity.com/t/max-results-and-context-annotations/156427/2?u=igorbrigadir

**Comment by cjbarrie** [comment]
Thanks, Igor. Yes we had the same problem a while back, which we resolved with what you recommend here (this was the reason for v0.2.1). I think
