### ISSUE TITLE
How to handle common errors

### ISSUE THREAD

**Issue by chainsawriot** [cjbarrie/academictwitteR#136]
**Is your feature request related to a problem? Please describe.**

Many of the issues that the developers need to deal with here are actually Twitter's problems, either Twitter's [server responses](https://developer.twitter.com/en/support/twitter-api/error-troubleshooting) or Twitter's [search engine limitations](https://twittercommunity.com/t/full-archive-search-by-language-pt-but-retrieve-other-languages/153116) (e.g. #135 #127 #108 #98 . ) Software packages like this encourage the users *not* to read the API documentation and offset the responsibilities to the developers of packages. It is actually bad for both the people using this package (how can one don't understand the API and use the data in one's research?) and the developers (it's out of developers' jurisdiction to "fix" Twitter's problems. The package has the ability to handle 429 [rate limit] and at least four 503 errors per request, but we can't "fix" something like 401 or persistent 503.)
 
**Describe the solution you'd like**

May I propose a FAQ-style guide on how to handle common errors? Especially for 5xx errors (just relax and chill...). 401 probably indicates a wrong bearer token (make sure you have copied the token correctly...) 401 indicates a bad query (e.g. start_time is later than end_time etc)

We can also talk about the limitations of the API, e.g. retweets are trimmed by default in V2 ( #108 ).

If it is a vignette, we can ask the users to read this vignette when [these common errors occur](https://github.com/cjbarrie/academictwitteR/blob/01d051e03d13f452be35ea0a2e30818ba8b1d773/R/utils.R#L56). If not, the wiki of this GitHub repo is a good place to host it too.

For things such as #108 , maybe we can also direct the users to ask them in [twittercommunity forum](https://twittercommunity.com/) instead.

**Comment by cjbarrie** [comment]
Yes I really like this solution. I also think relax and chill is good advice generally.

Happy to be assigned this task

**Comment by justinchuntingho** [comment]
That's an excellent idea. There has been a lot of issues that are not related to the source codes and hopefully this will resolve some issues before they are created. I think the wiki is a nice place to do it.

**Comment by cjbarrie** [comment]
Added vignette in #158
