### ISSUE TITLE
Continue previous query

### ISSUE THREAD

**Issue by justinchuntingho** [cjbarrie/academictwitteR#14]
Issue: If the system crashed amidst a search, there is currently no easy way to continue the data download without changing the query. It is possible to continue to continue by reading the existing tweets and find the last fetched by date/tweet id. It would be great to have a function to do that automatically.

Additional use case: The function can be used also for Twitter data monitoring/long period data collection. For example, it could be used to set up a loop to search new tweets every day. This could be particularly useful for tweets that has a tendancy to be removed (eg. bot, false information, other censored content etc).

**Comment by cjbarrie** [comment]
Fixed with `resume_collection()`
