### ISSUE TITLE
something went wrong. Status code: 400

### ISSUE THREAD

**Issue by PsychAnon** [cjbarrie/academictwitteR#152]
**Describe the bug**

install.packages("academictwitteR")
library(academictwitteR)

(bearer token from academic product track)
bearer_token <- "********************************************************"

self_care_tweets_2018_2021 <- 
    academictwitteR::get_all_tweets("selfcare OR #selfcare OR selflove OR #selflove OR loveyourself OR #loveyourself",
        is_retweet = FALSE, 
        country = "US",
        remove_promoted = TRUE, 
        has_links = FALSE, 
        has_media  = FALSE,
        lang = "en",
        "2018-01-01T00:00:00Z",
        "2021-01-01T00:00:00Z",
        n = 30000,
        bearer_token,
        bind_tweets = TRUE,
        file = "self_care_tweets_2018_2021")

**To Reproduce**

1. Open a new file.
2. Write down the provided code and run.
3. Get the error

**Expected behavior**
Should return 30000 tweets (provided that many exist, which I am pretty sure they do; I am nowhere near my 10,000,000 cap)

**Screenshots**
I don't think these are needed, but I am happy to provide them if requested.

**Additional context**
The code above is copied and pasted from Rstudio, so if there are errors in my original l code it should be reflected in this post.

R version 3.6.2 (2019-12-12)

**Comment by cjbarrie** [comment]
This is a bad request error. 

Not sure what version of academictwitteR you're using. But in the CRAN release `has_media` and `has_links` can't be `FALSE`. This isn't stopping your code running; it's just not doing anything.

The issue was how OR was specified. This was an error in the documentation. The following works:

```r

token = "AAAAAAAAAAAAAAAA"

tweets <-
  get_all_tweets(c("selfcare", "#selfcare", "selflove", "#selflove", "loveyourself", "#loveyourself"),
                                  is_retweet = FALSE,
                                  country = "US",
                                  remove_promoted = TRUE,
                                  lang = "en",
                                  "2018-01-01T00:00:00Z",
                                  "2021-01-01T00:00:00Z",
                                  bearer_token = token,
                                  bind_tweets = TRUE,
                                  file = "self_care_tweets_2018_2021")
```
