### ISSUE TITLE
Get user profile using keywords

### ISSUE THREAD

**Issue by yuanzhouIR** [cjbarrie/academictwitteR#154]
Hi there, thanks for developing this fantastic package! I'm wondering whether it is possible to retrieve user profile using keywords. For example, I want to collect the profile of all  Twitter users whose user name or description contains the phrase "political scientist". How should I do that?

**Comment by chainsawriot** [comment]
@yuanzhouIR API v2 doesn't provide this. Correct me if I'm wrong. AFAIK, v2's `GET users` endpoints do not include `search`, at least, yet. You need to [use v1](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-users-search).

**Comment by yuanzhouIR** [comment]
> @yuanzhouIR API v2 doesn't provide this. Correct me if I'm wrong. AFAIK, v2's `GET users` endpoints do not include `search`, at least, yet. You need to [use v1](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-users-search). Check [rtweet](https://docs.ropensci.org/rtweet/reference/search_users.html).

Thank you for the quick response! I think v2 supports both user id and user name lookup. However, the current version of this package can only get data using user id, right? Is it possible to retrieve users whose name contain the Chinese national flag 🇨🇳?

**Comment by chainsawriot** [comment]
@yuanzhouIR In Twitter's API documentation (`GET /2/users/by`), `usernames` means handles (e.g. `yuanzhouIR`), not names (e.g. Yuan Zhou).

**Comment by yuanzhouIR** [comment]
> @yuanzhouIR In Twitter's API documentation (`GET /2/users/by`), `usernames` means handles (e.g. `yuanzhouIR`), not names (e.g. Yuan Zhou).

I got it. Thank you! I'll try v1 via rtweet.
