### ISSUE TITLE
is_retweet=FALSE not working

### ISSUE THREAD

**Issue by benji700** [cjbarrie/academictwitteR#155]
is_retweet=FALSE within build_query doesn't seem to be working for me using either the developer version of the package or the standard version. 

Here's the code I'm using: 

mh_query <- build_query(query="#mentalhealth OR mental health",
                          is_retweet=F)

tweets_mh <-
  get_all_tweets(
    query=mh_query,
    "2021-06-07T09:55:00Z",
    "2021-06-07T10:00:00Z",
    bearer_token,data_path = 'data/',n=50
  )

which produces a dataset that includes retweets and the following output: "query: <#mentalhealth OR mental health  -is:retweet>: (tweets captured this page: 150). Total pages queried: 1. Total tweets ingested: 150. 
Amount of tweets exceeds  50 : finishing collection.
Warning messages:
1: Tweets will be bound in local memory as well as stored as JSONs. 
2: Directory already exists. Existing JSON files may be parsed and returned, choose a new path if this is not intended."

Thanks in advance!
Benji

**Comment by chainsawriot** [comment]
Please try this: 
```r
mh_query <- build_query(query="(#mentalhealth OR mental health)",
is_retweet=F)
```

**Comment by chainsawriot** [comment]
ref #136

**Comment by cjbarrie** [comment]
Updated with vignette in #158
