### ISSUE TITLE
Something went wrong. Status code: 401

### ISSUE THREAD

**Issue by strings678** [cjbarrie/academictwitteR#17]
Hi everyone, 

What does the above error mean? Trying to run the demo on # BLM tweets.

Thanks!

**Comment by justinchuntingho** [comment]
401 means [Unauthorized,](https://developer.twitter.com/en/support/labs/error-troubleshooting#:~:text=401%20Unauthorized,invalid%20consumer%20key%20or%20secret.) usually it means something wrong with the token? Could you check and see if you have used copy and paste the right bearer token from the academic product track?

**Comment by strings678** [comment]
Hi there, 

I simply copied my secret token?

Which of the **access_token, access_token_secret, consumer_key and consumer_secret** is the one which I need to use as the token?

Any help would be great, thanks.

**Comment by justinchuntingho** [comment]
In the Developer Portal, under the Keys and tokens tab of your app, there should be a field called "Bearer token". It is different from the secrets and tokens you have mentioned (they are for OAuth 1.0a).

**Comment by strings678** [comment]
Thanks for your help all!
