### ISSUE TITLE
Get user blocks

### ISSUE THREAD

**Issue by yuanzhouIR** [cjbarrie/academictwitteR#176]
The Twitter API v2 enables researchers to retrieve a list of blocked users by a specified user ID (https://developer.twitter.com/en/docs/twitter-api/users/blocks/api-reference/get-users-blocking). However, the get_user_blocks() function has not been created in this package, right? I would be grateful if someone can add this function.

**Comment by cjbarrie** [comment]
I don't think we intend to introduce this. From the documentation:

> The user’s ID must correspond to the user ID of the authenticating user, meaning that you must pass the Access Tokens associated with the user ID when authenticating your request.

In other words, you can only see who is blocked by the user if you have their auth. credentials. This basically means you can only see who your own account blocks. I don't think this is likely to be of much use for academic research
