### ISSUE TITLE
Only 100 tweets using get_all_tweets function

### ISSUE THREAD

**Issue by hsakareem** [cjbarrie/academictwitteR#179]
**Describe the bug**
I tried to download covid related tweets using the get_all_tweets function. I specified the date from 1st Jan 2020 to 1st July 2021. It only downloads 100 tweets.

**To Reproduce**
The code & results: 

> df_covid <- get_all_tweets("(#Covid) lang:en", "2020-01-01T00:00:00Z", "2021-07-01T00:00:00Z", bearer_token)
query:  (#Covid) lang:en 
Total pages queried: 1 (tweets captured this page: 500).
Total tweets captured now reach 100 : finishing collection.

**Expected behavior**
Clearly, there are thousands of tweets using #Covid. I needed all of them.

**Comment by cjbarrie** [comment]
You need to specify the n of tweets you wish to capture as described in https://cran.r-project.org/web/packages/academictwitteR/vignettes/academictwitteR-build.html
