### ISSUE TITLE
get_all_tweets only returns 100 tweets

### ISSUE THREAD

**Issue by tiangenglu** [cjbarrie/academictwitteR#185]
**Describe the bug**
Hi all,
I just downloaded the updated package today. But I'm now the `get_all_tweets` command only returns 100 tweet.

**To Reproduce**

`library(academictwitteR)
S281_2018_summer <- get_all_tweets(query = "#s281",start_tweets = "2018-05-19T00:00:00Z", end_tweets = "2018-09-18T00:00:00Z", bearer_token = bearer.token, bind_tweets = TRUE)`

`range(S281_2018_summer$created_at)
nrow(S281_2018_summer)`

[1] "2018-09-17T23:14:43.000Z" "2018-09-17T23:59:01.000Z"
[1] 100

**Expected behavior**
Full archive twitter data within the specified date range are expected to be retrieved using this command.

**Session Info:**
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.4

**Screenshots**
![image](https://user-images.githubusercontent.com/58899759/124813995-7b4e7e80-df33-11eb-9852-4183376ee029.png)

**Additional context**
Thank you for the diligent work of the developers.

Best,
Tiangeng

**Comment by chainsawriot** [comment]
Not a bug, that's a feature. `?get_all_tweets` and set `n = Inf`.

**Comment by tiangenglu** [comment]
> Not a bug, that's a feature. `?get_all_tweets` and set `n = Inf`.

Many thanks!
