### ISSUE TITLE
Simplified access to variables like coordinates and context annotations

### ISSUE THREAD

**Issue by benji700** [cjbarrie/academictwitteR#188]
**Is your feature request related to a problem? Please describe.**
I'm having some trouble un-nesting the geo and context annotations variables from the data frame returned by get_all_tweets().

**Describe the solution you'd like**
I could use a guide to un-nesting/un-listing those variables so I can access them like regular columns in a data frame. Alternately, if possible it would be helpful if get_all_tweets output those variables as columns instead of nested data frames / lists.

**Describe alternatives you've considered**
I've tried to use the unnest() and unlist() function on the output data frame in a few ways, but haven't had any luck. 

**Additional context**
Here's how the nested data looks in the data viewer and when called in the console:

<img width="816" alt="Screen Shot 2021-07-09 at 8 08 04 AM" src="https://user-images.githubusercontent.com/49567575/125099532-f5dee180-e08c-11eb-8ed3-6ccfeb422147.png">

<img width="325" alt="Screen Shot 2021-07-09 at 8 09 05 AM" src="https://user-images.githubusercontent.com/49567575/125099623-11e28300-e08d-11eb-8229-7dfa2d5eb394.png">

**Comment by cjbarrie** [comment]
Hey! Please follow the template guidelines on how to post an Issue. It's hard for us to know what the problem is unless you describe it in full, with examples

**Comment by benji700** [comment]
Ah, thank you for the heads up. I've edited the post now.

Best,
Benji

**Comment by chainsawriot** [comment]
@benji700 For `geo`, admittedly, I am still working on it. But for context annotations, the current versions (> 0.2) actually already have it. Whether or not it's `simplified` is of course debatable. But at least, it works. And you can then join it back to the main `tweets.main` data frame. However, `bind_tweets(output_format = "tidy")` doesn't deliver it. Sorry. (because it usually violates the 1NF)

``` r
require(academictwitteR)
#> Loading required package: academictwitteR
require(tibble)
#> Loading required package: tibble

bind_tweets(system.file("extdata", "tweetdata", package = "academictwitteR"), output_format = "raw") -> x

x$tweet.context_annotations
#> # A tibble: 2 x 6
#>   tweet_id   domain.id domain.name domain.description     entity.id  entity.name
#>   <chr>      <chr>     <chr>       <chr>                  <chr>      <chr>      
#> 1 140444092… 46        Brand Cate… Categories within Bra… 781974596… Services   
#> 2 140444092… 47        Brand       Brands and Companies   100452254… Twitter
```

<sup>Created on 2021-07-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by DrorWalt** [comment]
**As a temporary solution I've been using the following (somewhat non-efficient :-/) code:**

newtweets<-tweets %>% select(-c(entities,public_metrics,referenced_tweets,attachments,geo,withheld)) %>%
  cbind(tweets$public_metrics)

coords<-list()
for (i in 1:length(tweets$geo$coordinates$coordinates)) {
  if (length(tweets$geo$coordinates$coordinates[[i]])==0) {newval<-c(0,0)}
  else {newval=tweets$geo$coordinates$coordinates[[i]]}
  coords[[i]]<-newval
}
coords<-do.call(rbind,coords)
colnames(coords)<-c("coord_lon","coord_lat")
newtweets<-cbind(newtweets,coords)
