### ISSUE TITLE
For loop returning no data with get_user_profile

### ISSUE THREAD

**Issue by AlexHiscock56** [cjbarrie/academictwitteR#196]
#I'm trying to run get_user profile with author_ids drawn from a single column dataframe using the For loop to cycle through the list.

#Here is my code:

for(i in 1:nrow(Author_IDs))  #Author_IDs is the dataframe containing one column and 6667 rows of author_ids
{
Author_Data <- get_user_profile(i, bearer_token)
}

#It processes each request, then hits the rate limit, pauses and keeps going:
Processing from 1 to 1
Processing from 1 to 1
Processing from 1 to 1
Rate limit reached. Rate limit will reset at 2021-07-16 02:56:57 
Sleeping for 755 seconds. 
===============================================================================================Processing from 1 to 1
Processing from 1 to 1
Processing from 1 to 1
Processing from 1 to 1

# Then finishes with this:
Warning messages:
1: x-rate-limit-remaining=1. Resets at 2021-07-16 01:26:36 
2: x-rate-limit-remaining=1. Resets at 2021-07-16 01:41:39 
3: x-rate-limit-remaining=1. Resets at 2021-07-16 01:56:44 
4: x-rate-limit-remaining=1. Resets at 2021-07-16 02:11:47 
5: x-rate-limit-remaining=1. Resets at 2021-07-16 02:26:50 
6: x-rate-limit-remaining=1. Resets at 2021-07-16 02:41:53 
7: x-rate-limit-remaining=1. Resets at 2021-07-16 02:56:57 

# It also creates the Author_Data dataframe, but it's empty, with 0 obs of 0 variables. I've tried testing this with two IDs, and it works fine:
Author_Data <- get_user_profile(i, bearer_token)

#Is there an issue with my code, or is it a rate limit problem? Thanks for the help

**Comment by John-Kaz** [comment]
I've encountered a very [similar issue](https://github.com/cjbarrie/academictwitteR/discussions/195) the other day, only using `get_all_tweets`, looping through individual users. Not sure what is the reason underlying this.

**Comment by chainsawriot** [comment]
Of course your code doesn't work. Your for loop is looping through `i in 1:nrow(Author_IDs)` (i.e. 1,2,3,4.... nrow(Author_IDs))
And then you fetch for `get_user_profile(i, bearer_token)` where i = 1,2,3,4.... i.e. it is fetch user profile with `user_id` = 1,2,3 or so on.

Debug your code.
