### ISSUE TITLE
What's the best way to get tidy data or parse JSON output?

### ISSUE THREAD

**Issue by timroy** [cjbarrie/academictwitteR#20]
Is there a simple way to get tidy data or parse the JSON output from functions in this package? I may be missing something here but all methods that work with other Twitter-R packages aren't working here. I'm resorting to the following code:

`json_file <- rjson::fromJSON(file = "./data/data.json")`
`df <- stringi::stri_list2matrix(json_file, byrow = TRUE, fill = "") %>% data.frame()`

**Comment by eweisbrod** [comment]
I ended up writing a big ugly function that unnested each piece of the nested dataframe that was returned by the get_hashtag_tweets function.  I decided to store the nested data in separate flat tables that link back to the tweet-level data using tweet ID.  For example, if a tweet has 5 hastags, I have a hashtag table with 5 rows, one for each hashtag, and 5 rows have the same ID to link back to the text of the tweet.  I can share my code if it is helpful but more generally I followed this tutorial, which might be helpful to you:

https://hendrikvanb.gitlab.io/2018/07/nested_data-json_to_tibble/

This basic set of steps from the tutorial was useful to me:

  map_if(is.data.frame, list) %>% 
  as_tibble() %>% 
  unnest()

**Comment by justinchuntingho** [comment]
We recently added a new function to read the json and return a file dataframe. But as mentioned by @eweisbrod , the returned dataframe is filled with many other nested dataframes but most of the columns are fine (we are trying to find a way to deal with that). Assuming you saved your data into a folder named "data":

```
tweets <- bind_tweet_jsons(data_path = "data")
```

Hope this helps!

**Comment by tyskevdb** [comment]
> I ended up writing a big ugly function that unnested each piece of the nested dataframe that was returned by the get_hashtag_tweets function. I decided to store the nested data in separate flat tables that link back to the tweet-level data using tweet ID. For example, if a tweet has 5 hastags, I have a hashtag table with 5 rows, one for each hashtag, and 5 rows have the same ID to link back to the text of the tweet. I can share my code if it is helpful but more generally I followed this tutorial, which might be helpful to you:
> 
> https://hendrikvanb.gitlab.io/2018/07/nested_data-json_to_tibble/
> 
> This basic set of steps from the tutorial was useful to me:
> 
> map_if(is.data.frame, list) %>%
> as_tibble() %>%
> unnest()

Dear Eric,

I am struggling with the same issue for some time. I followed the steps of the helpful tutorial you shared, but got stuck. Could you share your code of your ugly (but working!) function to unnest each piece of the nested dataframe in separate tables? 

Thanks in advance!

**Comment by eweisbrod** [comment]
I took a shot at sharing my function as a gist:

https://gist.github.com/eweisbrod/6a3b4a914b59938d6cdce49decdd3b5a

This is my first time sharing a gist, so be gentle!  I think it only requires the tidyverse package, but I didn't have a chance to run an example and make sure everything runs fine when I pull this piece out of the rest of my code. 

I am happy to answer any questions if it doesn't work, or grateful for any suggestions to improve it. 

Hope this helps!
~Eric

**Comment by tyskevdb** [comment]
@eweisbrod 

Thank you for sharing! Really appreciated. The script works fine, except two errors. See my comment in your gist. 

Best,
Tijs

**Comment by eweisbrod** [comment]
@tyskevdb  
Thanks, I updated the code to add an example query. For me, it runs without error for this query. So, let me know if it runs for you on the same query.  Replied to your comment in the gist.
