### ISSUE TITLE
get retweets

### ISSUE THREAD

**Issue by TimBMK** [cjbarrie/academictwitteR#200]
Hey there! 

First of all thanks for the great package. It's made working with the V2 API so much easier for me! One functionality I'm missing, however, is conventiently getting all the retweets of a given tweet (comparable to rtweet's get_retweets). [The v2 API offers this functionality via the "/retweeted_by" endpoint.](https://developer.twitter.com/en/docs/twitter-api/tweets/retweets/api-reference)

Since I needed this functionality for a project I'm working on, I've frankensteined something together. It's just a change of endpoint in the [get_liking_users](https://github.com/cjbarrie/academictwitteR/blob/master/R/get_liking_users.R) function, but it seems to get the job done.  I'm sure there's a more elegant way to incorporate this function into the package though! 

Here's my makeshift code:
```
get_retweets_v2 <- function(x, bearer_token = get_bearer(), verbose = TRUE){
  bearer_token <- check_bearer(bearer_token)
  
  url <- "https://api.twitter.com/2/tweets/"
  
  endpoint <- "/retweeted_by"
  params <- list(
    "user.fields" = "created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,public_metrics,url,username,verified,withheld"
  )
  
  new_df <- data.frame()
  for(i in seq_along(x)){
    cat(paste0("Processing ",x[i],"\n"))
    requrl <- paste0(url,x[i],endpoint)
    next_token <- ""
    while(!is.null(next_token)) {
      if(next_token!=""){
        params[["pagination_token"]] <- next_token
      }
      dat <- make_query(url = requrl, params = params, bearer_token = bearer_token, verbose = verbose)
      next_token <- dat$meta$next_token #this is NULL if there are no pages left
      new_rows <- dat$data
      new_rows$from_id <- x[i]
      new_df <- dplyr::bind_rows(new_df, new_rows) # add new rows
      
      cat("Total data points: ",nrow(new_df), "\n")
      Sys.sleep(1)
      if (is.null(next_token)) {
        if(verbose) {
          cat("This is the last page for ",
              x[i],
              ": finishing collection. \n")
        }
        break
      }
    }
  }
  return(new_df)
}
```
I'd appreciate it if you could add something like this to the next version.

**Comment by chainsawriot** [comment]
@TimBMK Would you like to submit a pull request? For consistency, I think the function should be called `get_retweeted_by`

**Comment by TimBMK** [comment]
I will, as soon as I have the time to write a little failsave for it, e.g. by implementing the json streaming (great idea by the way, it's saved me multiple times already when scraping conversations) :)

**Comment by justinchuntingho** [comment]
I think it is better to avoid duplicating the query and saving bit (it will be very hard to maintain in the long run). A easier way is to pass everything through the `get_tweets()` function and all the querying and saving will be handled for you. An example would be: https://github.com/cjbarrie/academictwitteR/blob/master/R/count_all_tweets.R

Basically, for any new function in the future, we only need to create the `params` and `endpoint_url`.

And I plan to rework the `get_liking_users()` and other functions to this way too but I have managed to do so yet.
