### ISSUE TITLE
retweets are cut off mid sentence

### ISSUE THREAD

**Issue by patrickturlough** [cjbarrie/academictwitteR#21]
Hi,
when using your package to scrape tweets it seems like retweets are cut off in the middle of the sentence and the text just ends with "...", although when checking on the profile that retweeted something the full text is displayed. Everything else works fine and original tweets are fully displayed. This seems to bethe case when using get_user_tweets as well as get_hashtag_tweets.

**Comment by cjbarrie** [comment]
Thanks for this. It's a known issue. Retweets are stored in a separate referenced tweets field that need to be pulled back into the main data.frame to display properly. 

We can do so by adding an enhacement to e.g. "include full retweets." We're working on it!

**Comment by haylee-m** [comment]
Hello! Just wanted to mention to @patrickturlough, you can find the full text of the original Tweet in the users JSON. There is a 'tweet' object there. Inside you'll be able to find the full text of the RTs (yes it's a rather inconvenient place for it!)
