### ISSUE TITLE
[BUG] Make sure `make_query` run for at least 1s

### ISSUE THREAD

**Issue by thesickish** [cjbarrie/academictwitteR#231]
### Please confirm the following

- [X] I have searched the existing issues
- [X] The behaviour of the program is deviated from what is described in the documentation.
- [X] I can reproduce this problem for more than one time.
- [X] This is NOT a 3-digit error -- it does not display an error message like `something went wrong. Status code: 400.`
- [ ] This is a 3-digit error and I have consulted the [Understanding API errors](https://cran.r-project.org/web/packages/academictwitteR/vignettes/academictwitteR-errors.html) vignette and the suggestions do not help.

### Describe the bug

The package makes my computer sleep for a long period time in between queries (sometimes close to 15 minutes). This is happening when I run get_all_tweets several times in a row, even if I require the computer to sleep for 1.1 seconds in between queries. Each query is only asking for 15 tweets, and it sleeps after just 3 queries, so I do not think I am hitting any of the rate limits specified in the Twitter documentation. Is there a way to override the package's sleep specifications? This has only been happening recently, and with another computer that has an older version of the package installed I am not running into the same issue. Thanks for any insight into what might be happening!

### Expected Behavior

I am not expecting that the computer sleep after making 3 queries of 15 tweets each separated by 1.1 seconds.

### Steps To Reproduce

```markdown
# note: retweeters is an array of user IDs

for(i in 1:3)
{
	invisible(retw <-
  	try(get_all_tweets(
    	paste0("from:",retweeters[i]),
    	start_tweets = "2020-02-03T00:00:00Z",
    	end_tweets = "2020-11-03T00:00:00Z",
    	is_retweet = FALSE,
    	bearer_token,
    	page_n = 15,
    	n = 15,
    	data_path = "C:/Users/yotam/Documents/2020/try",
    	bind_tweets = FALSE
  )))
	Sys.sleep(1.1)
}
```

### Environment

```markdown
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringr_1.4.0         datetime_0.1.4        dplyr_1.0.7           rtweet_0.7.0         
[5] academictwitteR_0.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7       magrittr_2.0.1   usethis_2.0.1    tidyselect_1.1.1 R6_2.5.1        
 [6] rlang_0.4.11     fansi_0.5.0      httr_1.4.2       tools_4.1.1      utf8_1.2.2      
[11] ellipsis_0.3.2   tibble_3.1.3     lifecycle_1.0.0  crayon_1.4.1     purrr_0.3.4     
[16] vctrs_0.3.8      fs_1.5.0         curl_4.3.2       glue_1.4.2       stringi_1.7.3   
[21] compiler_4.1.1   pillar_1.6.2     generics_0.1.0   lubridate_1.7.10 jsonlite_1.7.2  
[26] pkgconfig_2.0.3
```

**Comment by chainsawriot** [comment]
@thesickish I don't expect it to sleep after 3 queries too. But could you please tell us the content of your `retweeters` vector? (Is it really an array? An R array is something like that: `array(1:3, c(2,4))`)

Using some other handles, I can't reproduce the error (You can also try the following reprex on your computer). Could you please also tell me the time zone of your computer and your current time?


``` r
require(academictwitteR)
#> Loading required package: academictwitteR
# Peter_Tolochko has a very empty timeline
retweeters <- c("Peter_Tolochko", "olivermb", "claesdevreese")
data_path <- academictwitteR:::.gen_random_dir()
for(i in 1:3)
{
  invisible(retw <-
              try(get_all_tweets(
                paste0("from:",retweeters[i]),
                start_tweets = "2020-02-03T00:00:00Z",
                end_tweets = "2020-11-03T00:00:00Z",
                is_retweet = FALSE,
                bearer_token = get_bearer(),
                page_n = 15,
                n = 15,
                data_path = data_path,
                bind_tweets = FALSE
              )))
  Sys.sleep(1.1)
}
#> query:  from:Peter_Tolochko -is:retweet 
#> Total pages queried: 1 (tweets captured this page: 0).
#> This is the last page for from:Peter_Tolochko -is:retweet : finishing collection.
#> Data stored as JSONs: use bind_tweets function to bundle into data.framequery:  from:olivermb -is:retweet
#> Warning: Directory already exists. Existing JSON files may be parsed and
#> returned, choose a new path if this is not intended.
#> Total pages queried: 1 (tweets captured this page: 15).
#> Total tweets captured now reach 15 : finishing collection.
#> Data stored as JSONs: use bind_tweets function to bundle into data.framequery:  from:claesdevreese -is:retweet
#> Warning: Directory already exists. Existing JSON files may be parsed and
#> returned, choose a new path if this is not intended.
#> Total pages queried: 1 (tweets captured this page: 15).
#> Total tweets captured now reach 15 : finishing collection.
#> Data stored as JSONs: use bind_tweets function to bundle into data.frame
```

<sup>Created on 2021-08-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by thesickish** [comment]
Hi there - I really appreciate the reply. The code seems to be working now.. I'm not sure what changed! I do think I misspoke and retweeters is not an array. Here are the contents of the first few entries (note: I've masked the actual screen names for anonymity):

> head(retweeters)
[1] "xxxxxxxxxx1" "xxxxxxxxxx2"   "xxxxxxxxxx3"   "xxxxxxxxxx4"   "xxxxxxxxxx5" 
[6] "xxxxxxxxxx6"

Here are the outputs of Sys.timezone() and Sys.time():

> Sys.timezone()
[1] "America/Phoenix"
> Sys.time()
[1] "2021-08-24 09:04:15 MST"

In any case, I'm no longer running into the issue, so I'll just keep collecting for now. Thanks again!

**Comment by thesickish** [comment]
Update: the computer is sleeping again, though this time after collecting data for many more handles (195 by my count). Perhaps I need to be sleeping more in between queries?

**Comment by thesickish** [comment]
OK, I guess the issue is not resolved.. it is now sleeping a second time (see screenshot below). Not sure what the fix is but for now my data collection seems interrupted. Any thoughts would be much appreciated!

![image](https://user-images.githubusercontent.com/3732054/130660002-f339b6d2-674d-4a48-8d3a-61188a89a2fa.png)

**Comment by chainsawriot** [comment]
@thesickish The problem could be our R code; but please keep in mind that Twitter API V2 itself is in early access. [Things like that](https://twittercommunity.com/t/getting-rate-limit-exceeded-error-without-exceeding-the-limits/153314) could occur. 

Do you have a systematic way to trigger this? If you have a systematic way to trigger this, it would be a nice idea to use the debugger of the helper function `make_query`, i.e.

```r
debug(academictwitteR:::make_query)
```

And then step through the execution. One important step is to inspect the status code and header part of the input parameter `r`. 

```r
httr::status_code(r)
httr::header(r)
```

If you can save a copy of the `r` which can trigger the sleeping that shouldn't (you can use `saveRDS` within the debugger), it would be very useful for our investigation.

**Comment by thesickish** [comment]
Thanks for the reply. I think I understand the trigger, though have not yet had a chance to run through the steps you mention. I think this is triggered when n = 15 and page_n = 15, and the first page picks up fewer than 15 tweet and the code immediately runs the same query again (to get to a total of n = 15 tweets). This results in two queries back-to-back for the same handle, and without the 1 second pause in between the two queries the longer sleep is triggered. I think one way of fixing this, though maybe cumbersome, is to sleep for 1 second between queries. I believe this is the rate limit specified in the academic twitter end point. I am wondering, though, if there might be a way to specify one page with a maximum of 15 tweets, so that if fewer than 15 are obtained there is no second query. This would be the equivalent of defining a max_pages parameter of 1. Anyway, I have to run off to teach but can try out some of your debugging suggestions a little later this week. Thanks again for your help!

**Comment by chainsawriot** [comment]
@thesickish If it is the case then I know what the bug is. It has been reported previously. (#195) We will get it fixed soon.

**Comment by chainsawriot** [comment]
The following is a reprex of the bug. The root cost is running two succesive calls to `make_query` less than 1s apart. And API has a rate limit of 1 call per 1s (or 15 calls per 15s). A solution is to make sure each `make_query` call running for at least 1s. Usually, it is. But for an empty response, it could be less than 1s.

```r

require(academictwitteR)
params <- 
list(query = "from:Peter_Tolochko -is:retweet", max_results = 15, 
     start_time = "2020-02-03T00:00:00Z", end_time = "2020-11-03T00:00:00Z", 
     tweet.fields = "attachments,author_id,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,public_metrics,possibly_sensitive,referenced_tweets,source,text,withheld", 
     user.fields = "created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,public_metrics,url,username,verified,withheld", 
     expansions = "author_id,entities.mentions.username,geo.place_id,in_reply_to_user_id,referenced_tweets.id,referenced_tweets.id.author_id", 
     place.fields = "contained_within,country,country_code,full_name,geo,id,name,place_type")
endpoint_url <- "https://api.twitter.com/2/tweets/search/all"
academictwitteR:::make_query(url = endpoint_url, params = params, bearer_token = get_bearer())
academictwitteR:::make_query(url = endpoint_url, params = params, bearer_token = get_bearer())
academictwitteR:::make_query(url = endpoint_url, params = params, bearer_token = get_bearer())
```

**Comment by thesickish** [comment]
Great! Thanks so much for the quick back and forth. I hope that gets to the bottom of it! Again, really appreciate the package and all of your help.

**Comment by chainsawriot** [comment]
@thesickish You may consider updating the package.
