### ISSUE TITLE
rate limit error

### ISSUE THREAD

**Issue by eweisbrod** [cjbarrie/academictwitteR#24]
**Describe the bug**

I got an error that seems to be related to the rate limit. I was using an lapply to apply get_hashtag_tweets to a list of search terms.

Error message:
Error in if (httr::headers(r)$`x-rate-limit-remaining` == "1") { : 
  argument is of length zero

**To Reproduce**
I don't know if I can reproduce it because I am not sure which rate limit I hit.  After waiting a bit, I retried the search term that failed, and it worked after waiting. 

**Expected behavior**
expected the search to return data without an error.

**Comment by t-davidson** [comment]
Hi @cjbarrie, this remains an issue, as I discovered this afternoon. It is also discussed in more detailed in [this post](https://github.com/cjbarrie/academictwitteR/issues/13). I think the simplest solution would be to add a parameter allowing the user to decide whether or not to store the results in memory.

**Comment by eweisbrod** [comment]
Yes, thanks. I have not personally gotten this specific error again, but I have been running some long queries that occasionally get 503 errors. Sometimes I wonder if it is really a 503 error because it seems to happen in the exact same part of the query every time. In any case, when the error occurs, I lose all the tweets that had been collected so far for that query. I agree with @t-davidson that an option to save the results in smaller batches or something like that would be helpful, or at least a way to output the tweets collected so far when an error occurs. For now I will try the workaround of running the query on smaller date ranges.

**Comment by t-davidson** [comment]
I'm currently running my query with a large data range but a smaller batch of accounts (50 at a time) and I have managed to avoid the error.

**Comment by justinchuntingho** [comment]
There is an option to save results in smaller per call and resume (See README.md, the Interruption and Continuation section).

**Comment by eweisbrod** [comment]
@justinchuntingho , thanks you guys are doing a great job. You are adding a lot of features at a pretty quick pace.

 I looked over the readme for the resume_collection command. It looks like it could be helpful, but I haven't fully wrapped my mind around it. Would it be possible to add an example of both the initial query with export_query = true and also the resume collection?  

Which option controls how often the results get saved to file ("...save results in smaller per call")?

Maybe in the example you could describe a query that got interrupted and what would be saved, what would be lost, and where it would pick back up on resume?  If that is too much documentation I understand. I am just giving my ideal wishlist.  Thanks again!
