### ISSUE TITLE
[BUG] <lang argument not passed in get_all_tweets>

### ISSUE THREAD

**Issue by LeWaHe** [cjbarrie/academictwitteR#251]
### Please confirm the following

- [X] I have searched the existing issues
- [X] The behaviour of the program is deviated from what is described in the documentation.
- [X] I can reproduce this problem for more than one time.
- [X] This is NOT a 3-digit error -- it does not display an error message like `something went wrong. Status code: 400.`
- [ ] This is a 3-digit error and I have consulted the [Understanding API errors](https://cran.r-project.org/web/packages/academictwitteR/vignettes/academictwitteR-errors.html) vignette and the suggestions do not help.

### Describe the bug

Get_all_tweets() does not seem to pass the lang argument.

### Expected Behavior

the query should only return tweets in language nl (Dutch), but it also returns French, English and Slovenian.

### Steps To Reproduce

library(academictwitteR)
get_bearer()

vaccine_NL <- get_all_tweets(query = "vaccinatie OR vaccin OR vaccineren",
                             start_tweets = "2021-11-01T00:00:00Z",
                             end_tweets = "2021-11-02T00:00:00Z",
                             file = "vaccine_NL",
                             n = 100,
                             is_retweet = FALSE,
                             country = "BE",
                             lang = "nl"
)
levels(as.factor(vaccine_FL$lang))
[1] "en" "fr" "nl" "sv"

### Environment

R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] academictwitteR_0.2.1

loaded via a namespace (and not attached):
 [1] magrittr_2.0.1   usethis_2.1.3    tidyselect_1.1.1 R6_2.5.1         rlang_0.4.12     fansi_0.5.0     
 [7] httr_1.4.2       dplyr_1.0.7      tools_4.1.2      utf8_1.2.2       DBI_1.1.1        ellipsis_0.3.2  
[13] assertthat_0.2.1 tibble_3.1.5     lifecycle_1.0.1  crayon_1.4.2     purrr_0.3.4      vctrs_0.3.8     
[19] fs_1.5.0         curl_4.3.2       glue_1.4.2       compiler_4.1.2   pillar_1.6.4     generics_0.1.1  
[25] jsonlite_1.7.2   pkgconfig_2.0.3

**Comment by chainsawriot** [comment]
ref #108 

@LeWaHe please understand that the Twitter API is [not perfect](https://twittercommunity.com/t/full-archive-search-by-language-pt-but-retrieve-other-languages/153116). Both the filtering and the language detection are far from perfect.

**Comment by LeWaHe** [comment]
@chainsawriot Thanks for the references to the topic, I will stick with the V1 API for now and continue doing post-collection custom filtering, although it is also far from perfect!
