### ISSUE TITLE
[BUG] bind_tweets error: column 'id' not found in '.data'

### ISSUE THREAD

**Issue by jcerrone** [cjbarrie/academictwitteR#290]
### Please confirm the following

- [X] I have searched the existing issues
- [X] The behaviour of the program is deviated from what is described in the documentation.
- [X] I can reproduce this problem for more than one time.
- [X] This is NOT a 3-digit error -- it does not display an error message like `something went wrong. Status code: 400.`
- [ ] This is a 3-digit error and I have consulted the [Understanding API errors](https://cran.r-project.org/web/packages/academictwitteR/vignettes/academictwitteR-errors.html) vignette and the suggestions do not help.

### Describe the bug

When running **bind_tweets**, I get an error message stating: "Column 'id' not found in '.data'." This appears similar to Issue #273, which appeared to have been resolved with a hot fix--but that post did not provide steps I can take to address a reoccurrence of the issue. The code I'm using is:

**To Get Tweets**
```
spain_parties <- c("20509689", "50982086", "2288138575", 
                   "19028805", "2201623465", "14824411",
                   "146150851")

get_all_tweets(
  user = spain_parties,
  start_tweets = "2007-08-01T00:00:00Z",
  end_tweets = "2022-01-01T00:00:00Z",
  data_path = "~/Desktop/Research/ZData/Twitter Archives/",
  bind_tweets = FALSE,
  n = Inf
)
```

**To Bind Tweets**
```
tweets_spain_parties <- bind_tweets(data_path = "~/Desktop/Research/ZData/Twitter Archives/",
                                    output_format = "tidy")
```

**Error Messages**
```
rlang::last_error()
<error/rlang_error_data_pronoun_not_found>
Column `id` not found in `.data`
Backtrace:
  1. academictwitteR::bind_tweets(...)
 29. rlang:::abort_data_pronoun(x)
Run `rlang::last_trace()` to see the full context.
rlang::last_trace()
<error/rlang_error_data_pronoun_not_found>
Column `id` not found in `.data`
Backtrace:
     █
  1. ├─academictwitteR::bind_tweets(...)
  2. │ └─academictwitteR:::.flat(data_path, output_format = output_format)
  3. │   └─purrr::map_dfr(data_files, convert_json, output_format = output_format)
  4. │     └─purrr::map(.x, .f, ...)
  5. │       └─academictwitteR:::.f(.x[[i]], ...)
  6. │         ├─`%>%`(...)
  7. │         ├─dplyr::select(...)
  8. │         └─dplyr:::select.data.frame(...)
  9. │           └─tidyselect::eval_select(expr(c(...)), .data)
 10. │             └─tidyselect:::eval_select_impl(...)
 11. │               ├─tidyselect:::with_subscript_errors(...)
 12. │               │ ├─base::tryCatch(...)
 13. │               │ │ └─base:::tryCatchList(expr, classes, parentenv, handlers)
 14. │               │ │   └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
 15. │               │ │     └─base:::doTryCatch(return(expr), name, parentenv, handler)
 16. │               │ └─tidyselect:::instrument_base_errors(expr)
 17. │               │   └─base::withCallingHandlers(...)
 18. │               └─tidyselect:::vars_select_eval(...)
 19. │                 └─tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 20. │                   └─tidyselect:::eval_c(expr, data_mask, context_mask)
 21. │                     └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
 22. │                       └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
 23. │                         └─base::eval(expr, data_mask)
 24. │                           └─base::eval(expr, data_mask)
 25. │                             ├─id
 26. │                             └─rlang:::`$.rlang_data_pronoun`(.data, id)
 27. │                               └─rlang:::data_pronoun_get(x, nm)
 28. ├─dplyr::distinct(., .data$id, .keep_all = TRUE)
 29. └─rlang:::abort_data_pronoun(x)
```

### Expected Behavior

I expected **bind_tweets** to produce a tidy dataframe with the data stored in the json files.

### Steps To Reproduce

reprex::reprex()
#> x Install the styler package in order to use `style = TRUE`.
#> ℹ Non-interactive session, setting `html_preview = FALSE`.
#> CLIPR_ALLOW has not been set, so clipr will not run interactively
#> Error in switch(where, expr = stringify_expression(x_expr), clipboard = ingest_clipboard(), : EXPR must be a length 1 vector

### Environment

sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.5.2

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] forcats_0.5.1         stringr_1.4.0         dplyr_1.0.7           purrr_0.3.4          
 [5] readr_2.0.1           tidyr_1.1.3           tibble_3.1.4          ggplot2_3.3.5        
 [9] tidyverse_1.3.1       academictwitteR_0.3.0

loaded via a namespace (and not attached):
 [1] tidyselect_1.1.1 xfun_0.25        haven_2.4.3      colorspace_2.0-2 vctrs_0.3.8      generics_0.1.0  
 [7] usethis_2.0.1    htmltools_0.5.2  yaml_2.2.1       utf8_1.2.2       rlang_0.4.11     pillar_1.6.2    
[13] glue_1.4.2       withr_2.4.2      DBI_1.1.1        dbplyr_2.1.1     modelr_0.1.8     readxl_1.3.1    
[19] lifecycle_1.0.0  munsell_0.5.0    gtable_0.3.0     cellranger_1.1.0 rvest_1.0.1      evaluate_0.14   
[25] knitr_1.34       callr_3.7.0      fastmap_1.1.0    tzdb_0.1.2       ps_1.6.0         fansi_0.5.0     
[31] highr_0.9        broom_0.7.9      Rcpp_1.0.7       clipr_0.7.1      scales_1.1.1     backports_1.2.1 
[37] jsonlite_1.7.2   fs_1.5.0         digest_0.6.27    hms_1.1.0        stringi_1.7.4    processx_3.5.2  
[43] grid_4.1.1       cli_3.0.1        tools_4.1.1      magrittr_2.0.1   crayon_1.4.1     pkgconfig_2.0.3 
[49] ellipsis_0.3.2   xml2_1.3.2       reprex_2.0.1     lubridate_1.7.10 assertthat_0.2.1 rmarkdown_2.10  
[55] httr_1.4.2       rstudioapi_0.13  R6_2.5.1         compiler_4.1.1  

### Anything else?

Thank you in advance for your help!

**Comment by cjbarrie** [comment]
Hi. It's hard to reproduce this exact query as it will involve extensive data collection on our part. I have tested with the following query:

```r
library(academictwitteR)

spain_parties <- c("20509689", "50982086", "2288138575", 
                   "19028805", "2201623465", "14824411",
                   "146150851")

get_all_tweets(
  user = spain_parties,
  start_tweets = "2022-01-01T00:00:00Z",
  end_tweets = "2022-01-08T00:00:00Z",
  data_path = "data/",
  bind_tweets = FALSE,
  n = Inf
)

tweets_spain_parties <- bind_tweets(data_path = "data/",
                                    output_format = "tidy")

```

and  I don't get any error. My guess was that id fields may not be included in particularly old tweet fields. But this does not seem to be the case as I'm also not able to replicate using only old tweet queries for these users.

**Comment by jcerrone** [comment]
Thanks for your quick response! I was able to successfully run the code using the abridged data in your example, so I assume the problem is hidden somewhere in the files. I think my best course of action is to download and process the data in smaller batches and hopefully identify any problems that way.

**Comment by chainsawriot** [comment]
@jcerrone If you can, share with me your "~/Desktop/Research/ZData/Twitter Archives/". Then I can pinpoint which json file is problematic. Or else we won't able to help.
Find my e-mail in the DESCRIPTION file.

**Comment by jcerrone** [comment]
@chainsawriot just sent you an email--thanks for the help!

**Comment by chainsawriot** [comment]
Probably a duplicate of #273 , can't reproduce with the patched Github version.
Awaiting @jcerrone 's confirmation.

**Comment by jcerrone** [comment]
Using the developer version from GitHub worked! Thanks again!
