### ISSUE TITLE
[FR] Profile geolocation

### ISSUE THREAD

**Issue by margauxw** [cjbarrie/academictwitteR#291]
### Describe the solution you'd like

I'd really like to know how I can search on profile_region and profile_location

**Comment by chainsawriot** [comment]
@margauxw 

Two options

1. Use Premium 1.1 API (fee might apply) and see if our aunt [offers anything](https://search.r-project.org/CRAN/refmans/rtweet/html/search_users.html). 
2. [Wait for the placement of it in the v2 API from Twitter](https://developer.twitter.com/en/docs/twitter-api/migrate/twitter-api-endpoint-map).
