### ISSUE TITLE
Allow specified tweet and user fields

### ISSUE THREAD

**Issue by cjbarrie** [cjbarrie/academictwitteR#5]
Feature: Allow user to fetch only specified tweet- and user-level fields

Solution: Add options that alter query parameters to include only specified user fields. Could be in form of series of addition functions e.g. get_users and get_tweets as well as more specific e.g. get_user_metrics to just capture user following, listed, tweet count etc. or, for tweets, get_tweet_entities to just capture tweet annotations, mentions, hashtags etc.

**Comment by bdong-CLS** [comment]
Thank you in advance and I am relatively new to Github.  

I have been using the "get_hashtag_tweets" function recently (thanks a lot!) but wonder if the function only provides information from tweet.fields as a data frame (when not specifying the file string and data_path string).   The original "get_tweets" function includes tweet.fields, user.fields, expansions, and place.fields in the parameters lists.  And when I use the "get_tweets" function, I do get a list of length 4: data, includes, errors, and meta (though it does not come with automatic pagination).   When I use "get_hashtag_tweets" function, it seems to me that only response fields from tweet.fields are presented in the data frame. 
        
Did I miss something or do something wrong?  For example, right now, I can only see "author_id" without knowing "name" or "username" in the data frame after "get_hashtag_tweets". 

Thank you again!

**Comment by justinchuntingho** [comment]
The user fields are not parsed and therefore not returned by the function. It would be possible to get back the names by the function in PR #12 . I think it makes sense to parse and return some user data or add option to control what is returned. Let me look into it.

**Comment by bdong-CLS** [comment]
Thanks for the reply! Appreciate it. 

Thanks a lot again for working on "academictwitteR".
