### ISSUE TITLE
Failed to install 'academictwitteR' from GitHub

### ISSUE THREAD

**Issue by anamartinovici** [cjbarrie/academictwitteR#59]
**Describe the bug**
![image](https://user-images.githubusercontent.com/20222657/116565019-c16cdd80-a905-11eb-97e6-8dbf122bb06f.png)

**To Reproduce**
1. Open a new RStudio session
2. Type `devtools::install_github("cjbarrie/academictwitteR", build_vignettes = TRUE)` in the console, as explained in `https://github.com/cjbarrie/academictwitteR/blob/master/README.md#installation`
3. Press "Enter"

**Expected behavior**
I was expecting that the package would be installed.

**Screenshots**
See above.

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/20222657/116565482-36d8ae00-a906-11eb-9265-2d17a38bd5f0.png)

**Comment by cjbarrie** [comment]
Hi. I couldn't reproduce this. Does this remain a problem?

**Comment by anamartinovici** [comment]
I have tried again now and the installation was successful, so the issue is no longer present for the current version of the repo. I am closing the issue.
