### ISSUE TITLE
get_radius_tweets confusion

### ISSUE THREAD

**Issue by datawranglingUCSBecon** [cjbarrie/academictwitteR#62]
Hello,

I am using the `get_radius_tweets` command and am getting tweets that aren't in my specified radius. For example, see the code below:

``
test1<-get_radius_tweets(
  c("#proudboys","#pyob","proud boys"),
  radius=c(-121.4962,38.5799,10), # Sacramento city center
  start_tweets = "2020-11-03T00:00:00Z", 
  end_tweets = "2020-11-10T10:00:00Z",
  bearer_token = bearer_token,
  data_path = "data/"
)
``

When I inspect the geo-coordinates, most are blank. Those that are nowhere near Sacramento. For example, one tweet has the following geo-coordinates: `c(-70.03333333, 12.51666667)`. Am I doing something wrong?

Thanks!

**Comment by cjbarrie** [comment]
Thanks for posting this Issue. I don't have a great answer at this stage. Most coordinates will be blank as place is identified from other fields as well e.g. place name in a bio etc. and then attributed back. 

See details here: https://developer.twitter.com/en/docs/tutorials/filtering-tweets-by-location. I'm not sure why these tweets would be capture when they're clearly outside the specified radius. Will add this to list of questions to pose to Twitter Dev Board
