### ISSUE TITLE
429 Error - get_user_tweets

### ISSUE THREAD

**Issue by HohnerJulian** [cjbarrie/academictwitteR#63]
Hi Christopher Barrie and Justin Chun-ting Ho,

First of all, thank you for providing this package! I just used your package to download tweets from a large list of accounts (502 accounts separated in ~ 100 accounts per list to reduce the amount of tweets per request). 

However, when downloading tweets from one list (doesn't matter what list i specifiy), it stops after it iterated through approx. 30 accounts. The error message is "Error in get_tweets(q = query, n = 500, start_time = start_tweets, end_time = end_tweets, : something went wrong. Status code: 429" 

The code 429 refers to "too many requests", even though my limit isn't reached at all. So if the maximum amount isn't reached, the problem probably is due to the rate I request data. Can I somehow specificy f.e. "RetryonLimit = TRUE" or do you have a workaround for this problem? 

Many Thanks in advance and keep up the awesome work! 

Kind regards 

Juilian

**Comment by cjbarrie** [comment]
Thanks for reporting this, Julian. Seems odd you would get this error... We will add to our TODO list to add a manual rate limit retry option
