### ISSUE TITLE
"get_all_tweets" doesn't work for me

### ISSUE THREAD

**Issue by SergeLuther** [cjbarrie/academictwitteR#66]
**Describe the bug**
Thanks a lot for providing this package.
I was replicating your following  codes:

# Insert bearer token
bearer_token<-"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

tweets <-  get_all_tweets("apples OR oranges","2020-01-01T00:00:00Z","2020-01-05T00:00:00Z",bearer_token)

But I got the following error message:

Error: Argument 1 can't be a list containing data frames

Please can you explain me why I got this message?

Thanks,

Best.

**Comment by datawranglingUCSBecon** [comment]
Your code worked on my machine. Try restarting `R`? If not, maybe try using paranthese like this:

tweets <- get_all_tweets("(apples OR oranges)","2020-01-01T00:00:00Z","2020-01-05T00:00:00Z",bearer_token)

**Comment by cjbarrie** [comment]
Also unable to reproduce this error. Could you update on whether still an issue?

**Comment by SangJungKim** [comment]
I have tried on mac, and got the same issue:

devtools::install_github("cjbarrie/academictwitteR", build_vignettes = TRUE)
library("academictwitteR")

bearer_token = "MY BEARER TOKEN"

tweets <- get_all_tweets("(Medical marijuana OR Medicated cake)",
                         "2020-12-31T00:00:00Z",
                         "2020-12-31T23:59:59Z",
                         bearer_token,
                         lang = "en",
                         data_path = "2020-12",
                         bind_tweets = FALSE)

> tweets <- get_all_tweets("(Medical marijuana OR Medicated cake)",
+                          "2020-12-31T00:00:00Z",
+                          "2020-12-31T23:59:59Z",
+                          bearer_token,
+                          lang = "en",
+                          data_path = "2020-12",
+                          bind_tweets = FALSE)
Error: Argument 2 can't be a list containing data frames

**Comment by justinchuntingho** [comment]
Could you share what you got with `sessionInfo()`?

**Comment by sidelnikov-alexey** [comment]
I got
`Error in bind_rows_(x, .id) : 
  Argument 4 can't be a list containing data frames` as well on MAC. I tried windows as well and it did not help.

I tried to run this code
```
install.packages("academictwitteR")
library("academictwitteR")
tweets <- get_all_tweets("(apples OR oranges)", "2020-01-01T00:00:00Z", "2020-01-05T00:00:00Z", bearer_token)
```

This is my sessionInfo()
```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] academictwitteR_0.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18     crayon_1.3.4     dplyr_0.7.6      assertthat_0.2.0 R6_2.2.2         jsonlite_1.5     magrittr_1.5    
 [8] pillar_1.3.0     httr_1.3.1       rlang_0.2.2      curl_3.2         bindrcpp_0.2.2   tools_3.5.1      glue_1.3.0      
[15] purrr_0.2.5      compiler_3.5.1   pkgconfig_2.0.2  tidyselect_0.2.4 bindr_0.1.1      tibble_1.4.2    

```

**Comment by SangJungKim** [comment]
I have tried after updating packages, and I got another error. 

> tweets <- get_all_tweets("apples OR oranges",
+                          "2020-12-31T23:00:00Z",
+                          "2020-12-31T23:59:59Z",
+                          bearer_token,
+                          lang = "en",
+                          data_path = "trial1",
+                          bind_tweets = FALSE)
Error in get_tweets(q = built_query, n = 500, start_time = start_tweets,  : 
  something went wrong. Status code: 429
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)


This is my session info:

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] academictwitteR_0.1.0

loaded via a namespace (and not attached):
[1] httr_1.4.2     compiler_3.6.2 R6_2.5.0       tools_3.6.2    curl_4.3.1   

I think status 429 is not solved?

**Comment by justinchuntingho** [comment]
@SangJungKim Thanks for reporting. Status code: 429 means 'Too many requests' error. You have reached your rate limit, probably because you are running the tests. Can you wait 15 minutes (after the rate limit resets) and try again?

@sidelnikov-alexey I realise you have dplyr 0.7.6 installed, can you update dplyr and try again? 

@cjbarrie If it is indeed the older version of `dplyr::bind_rows()` causing the problem, we might need to specify a dplyr version in the dependencies.

**Comment by sidelnikov-alexey** [comment]
@justinchuntingho thank you for your reply. It actually did not work but I found out why. My R version was too old. Updating the R version made a trick and everything works just fine now.

**Comment by SangJungKim** [comment]
My rate limit for the month is now running again, but I got another error with 503: total pages queried: 5. Total tweets ingested: 2392. 
Error in get_tweets(q = built_query, n = 500, start_time = start_tweets,  : 
  something went wrong. Status code: 503

What should I do with this case?

**Comment by justinchuntingho** [comment]
This is a good sign since I can see you are getting some tweets.

503 means "The Twitter servers are up, but overloaded with requests" (see https://developer.twitter.com/ja/docs/basics/response-codes). Could you try again later?

**Comment by SangJungKim** [comment]
I tried two more times, and I am still getting 503 errors while fetching 60,000 tweets / 50,000 tweets. I heard other researchers also getting errors and there is one problematic minute from 00:00:00 to 00:00:01.

**Comment by HohnerJulian** [comment]
This is a known issue with the twitter servers: https://twitter.com/suhemparack/status/1394699206510608389 and I am also currently struggling with it.

As described by Suhem Parack, the issue might resolve by requesting only 100 tweets per request instead of 500. However, i can't find an option to specify this in the package. @justinchuntingho or @cjbarrie might help here?

**Comment by justinchuntingho** [comment]
Thanks for letting us know @HohnerJulian, I was not aware of the issue. I have added a new argument "page_n" to specify the amount of tweets per request #77 . Could you try to install the PR using `devtools::install_github("cjbarrie/academictwitteR#77")` and try? In your script, add `page_n = 100` as an argument and it should change the amount to 100 tweets per request.

**Comment by SangJungKim** [comment]
I tried page_n = 100, and I am still getting the following error:
Total pages queried: 74. Total tweets ingested: 7068. 
Error in get_tweets(q = built_query, n = page_n, start_time = start_tweets,  : 
  something went wrong. Status code: 503

**Comment by SergeLuther** [comment]
The problem is fixed now. Just need to update my R version. Thanks a lot.
