### ISSUE TITLE
get_all_tweets: error if not tweets are returned

### ISSUE THREAD

**Issue by davidemorselli** [cjbarrie/academictwitteR#88]
the get_all_tweets gives an error and stops if not tweets are retrieved for a specific time window

Tweets will be bound in local memory as well as stored as JSONs.Directory already exists. Existing JSON files may be parsed and returned, choose a new path if this is not intended.query: <#Figliuolo -is:retweet lang:it>: (tweets captured this page: ). Total pages queried: 1. Total tweets ingested: . 
Error in if (ntweets > n) { : argument is of length zero

**To Reproduce**
get_all_tweets(#Figliuolo,
  "2020-12-01T00:00:00Z",
  "2020-12-31T00:00:00Z",
  bearer_token, n=100000, data_path=newDir, lang = "it")

I'm using the github version 0.2.0

**Comment by justinchuntingho** [comment]
Thanks for reporting! This is indeed a bug. I should check if ntweets equals to zero before doing the (ntweets > n) evaluation. Let me create a fix soon.

**Comment by eweisbrod** [comment]
yes I ran into this bug too, thanks

**Comment by chainsawriot** [comment]
I've tried to fix this. @davidemorselli 's case is used as a test case in the test suite. But admittedly, corner cases like this are still not well-tested. Could you please give it a try and see if the problem persists?

**Comment by davidemorselli** [comment]
great thanks!I'll test it in the next days. BTW any chance you can free the options to the all of the fromJson function? now get_all_tweets returns a very nested data table (a data frame which includes other data frames which include other data frames). to solve the problem I have basically to resave in json and reimport it with flatten=TRUE..On Jun 12, 2021 15:27, Chung-hong Chan ***@***.***> wrote:
I've tried to fix this. @davidemorselli 's case is used as a test case in the test suite. But admittedly, corner cases like this are still not well-tested. Could you please give it a try and see if the problem persists?

**Comment by eweisbrod** [comment]
I think this is fixed now. It looks like it just runs successfully and prints "...Total tweets ingested: 0." now.

**Comment by chainsawriot** [comment]
@eweisbrod Thanks for reporting. Then I close this.
