### ISSUE TITLE
Issue with bearer_token error message

### ISSUE THREAD

**Issue by sutter-cane** [cjbarrie/academictwitteR#9]
After having installed the development package devtools::install_github("cjbarrie/academictwitteR") 
and activated the library by running the code library("academictwitteR"). After that I ran the following commands:
`bearer_token <- "long sequence of numbers and letters"` (It ran with no error, got registered in Values)
`boycott_tweets <- get_hashtag_tweets("#boycott", bearer_token)` and receiever the following:

> Error in get_tweets(q = query, n = 500, start_time = start_tweets, end_time = end_tweets,  : 
>                       bearer token must be specified.
 
I specified it already. However, I go to my Twitter developer project and revoke the bearer token. 
Having changed the bearer token in my code chunk, and I run it again. bearer_token is replaced with the new one in Values. 
I now run `boycott_tweets <- get_hashtag_tweets("#boycott", bearer_token)` but it feeds me back the same error above. 

**Desktop:**
 - OS: iOS Big Sur Version 11.2.2 (20D80)
 - Browser safari Version 14.0.3 (16610.4.3.1.4)

**Comment by cjbarrie** [comment]
I think this is an issue with not specifying a date range. Try e.g.: 

get_hashtag_tweets("#boycott", "2020-01-01T00:00:00Z", "2020-01-02T00:00:00Z", bearer_token)

We need to change the error message to reflect this

**Comment by sutter-cane** [comment]
I have changed the command to reflect your suggested changes. 
I am running the following command:
`boycott_tweets <- get_hashtag_tweets("#boycott", "2020-01-01T00:00:00Z", "2020-01-02T00:00:00Z", bearer_token)
The command did not run feeding back the following error message: 
> `Error in get_tweets(q = query, n = 500, start_time = start_tweets, end_time = end_tweets,  : 
>   something went wrong. Status code: 403

**Comment by justinchuntingho** [comment]
I just tried the following codes and it works on my end:
```boycott_tweets <- get_hashtag_tweets("#boycott", "2020-01-01T00:00:00Z", "2020-01-02T00:00:00Z", bearer_token)```

Error code 403 seems to stand for a correct request but access denied. Just to confirm, does the bearer token come from an App within the Academic Product Track and the monthly tweet cap is not exceeded?

**Comment by sutter-cane** [comment]
Hi there, thanks for your response. No, it is not the Academic Product Track, it is the Standard product track. I did not exceed the monthly tweet cap because I did not manage to run the code successfully.

**Comment by justinchuntingho** [comment]
The package calls the full-archive search endpoint and therefore it will only work for the Academic Product Track, hence the error message. You could apply for access [here](https://developer.twitter.com/en/solutions/academic-research/products-for-researchers) and after that you should be able to create a new app under the Academic Product Track.

**Comment by sutter-cane** [comment]
Thanks. My application was pending but got approved today. I have tried running the code and it is working.
