### ISSUE TITLE
cannot bind json

### ISSUE THREAD

**Issue by psalmuel19** [cjbarrie/academictwitteR#91]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by psalmuel19** [comment]
Hi,
My attempt to bind the data returned using search_tweets <- bind_tweet_jsons(data_path = "endsars_tweets") failed.
Here is the error:
search_tweets <- bind_tweet_jsons(data_path = "endsars_tweets")
Error in open.connection(con, "rb") : cannot open the connection
In addition: Warning messages:
1: In file(path) :
  'raw = FALSE' but 'endsars_tweets' is not a regular file
2: In open.connection(con, "rb") :
  cannot open file 'endsars_tweets': it is a directory
>
Seems if the JSONs are saved as something other than "data_" then the function won't find them. Anyone else experienced same?
Chris has been in touch and trying to help resolve this. Thanks Chris!

**Comment by cjbarrie** [comment]
Hi Psalmuel: can you include the original get_all_tweets() call that you used to retrieve the data?

**Comment by psalmuel19** [comment]
search_tweets <- get_all_tweets("#EndSARS",
                                "2020-10-16T09:00:00Z",
                                "2020-10-17T09:30:00Z",
                                bearer_token,
                                data_path = "endsars_tweets",
                                bind_tweets = FALSE
)

**Comment by cjbarrie** [comment]
Hi Psalmuel. This code is, in fact, working fine for me.

```
library(academictwitteR)
setwd("/Users/cbarrie6/Dropbox/sandbox/tweetstreams/academictwitteR_test")

bearer_token = "XXXXXXXINSERTBEARERTOKENXXXXXXXX"

search_tweets <- get_all_tweets("#EndSARS",
                                "2020-10-16T09:00:00Z",
                                "2020-10-17T09:30:00Z",
                                bearer_token,
                                data_path = "endsars_tweets",
                                bind_tweets = FALSE
)

search_tweets <- bind_tweet_jsons(data_path = "endsars_tweets")
```

The tweets when I run this code are correctly saved with the prefix "data_" so I am not sure, from your previous communication, why your JSONs are stored with the prefix "endsars_tweets." Is the above definitely the code you used?

**Comment by psalmuel19** [comment]
Hi Chris,

That is the code I used. I just tried again and it saves the JSON with the prefix "endsars_tweets". Here is one of the files "endsars_tweetsdata_1317397352441937920"

**Comment by psalmuel19** [comment]
Here is what I used:

library(academictwitteR)
setwd("/Users/samuelola/Downloads/R/endsars_tweets/")

search_tweets <- get_all_tweets("#EndSARS",
                                "2020-10-16T09:00:00Z",
                                "2020-10-17T09:30:00Z",
                                bearer_token,
                                data_path = "endsars_tweets",
                                bind_tweets = FALSE
)

search_tweets <- bind_tweet_jsons(data_path = "endsars_tweets")

**Comment by psalmuel19** [comment]
> search_tweets <- bind_tweet_jsons(data_path = "endsars_tweets")
Error in open.connection(con, "rb") : cannot open the connection
In addition: Warning messages:
1: In file(path) :
  'raw = FALSE' but 'endsars_tweets/' is not a regular file
2: In open.connection(con, "rb") :

**Comment by cjbarrie** [comment]
@justinchuntingho is this code working as expected for you as well? I am a bit stumped. I don't understand why the JSONs are being stored with a different prefix... @psalmuel19 are you using the CRAN release or the development version? I have tried both, however, and they are both working as expected

**Comment by psalmuel19** [comment]
Not sure. How can I confirm that please? I am really sorry for all my troubles Chris

**Comment by psalmuel19** [comment]
Update:
Seemed to be working and then returned this error:

search_tweets <- bind_tweet_jsons(data_path = "/Users/samuelola/Downloads/R/endsars_tweets")
========================================
 Error: Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.
Run `rlang::last_error()` to see where the error occurred.

**Comment by psalmuel19** [comment]
rlang::last_error()
<error/rlang_error>
Internal error in `vec_assign()`: `value` should have been recycled to fit `x`.
Backtrace:
 1. global::bind_tweet_jsons(data_path = "/Users/samuelola/Downloads/R/endsars_tweets")
 2. dplyr::bind_rows(json.df.all, json.df)
 3. vctrs::vec_rbind(!!!dots, .names_to = .id)
Run `rlang::last_trace()` to see the full context.
>

**Comment by medewitt** [comment]
Might be a dplyr::bind_rows issue. See <https://github.com/r-lib/vctrs/issues/1073>

**Comment by psalmuel19** [comment]
Thanks all, it has worked and I am able to write it into data frame. @cjbarrie I appreciate your patience and help.
