### ISSUE TITLE
get_liked_tweets

### ISSUE THREAD

**Issue by asunarja** [cjbarrie/academictwitteR#93]
Cannot find the get_liked_tweets function

**Comment by cjbarrie** [comment]
Hi: we need more information to be able to help. Please follow the template for posting an Issue: e.g., what version of the package are you using, what is your session info., what is the error you're getting... See other Issues for an example

**Comment by asunarja** [comment]
Hello,

I'm using academictwitteR package version 0.1.0. For the operating system, I'm using IOS

I've successfully used get_user_tweets function however, when I was trying to use get_liked_tweets I got this error message

"could not find function "get_liked_tweets" which seems that it does not recognize as a part of the package. 

Any help is appreciated. Thank you!

**Comment by cjbarrie** [comment]
Hey: this function is only ready for use in the development version. We should be releasing to CRAN soon. Or you can try install the development version with the`install_github` code in the README page.
