### ISSUE TITLE
something went wrong. Status code: 403

### ISSUE THREAD

**Issue by AbrarJahin** [cjbarrie/academictwitteR#98]
**Describe the bug**
My code is simple-

````
install.packages("academictwitteR")
library(academictwitteR)

bearer_token <- "********************************************************"

tweets <-
  get_all_tweets(
    "#BLM OR #BlackLivesMatter",
    "2014-01-01T00:00:00Z",
    "2020-01-01T00:00:00Z",
    bearer_token,
    data_path = "data/",
    bind_tweets = FALSE
  )
````

Then I am getting this-

![image](https://user-images.githubusercontent.com/4152843/120937250-85822080-c6da-11eb-8ac5-c1177d349774.png)

Can anyone please help?

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a new file.
2. Write down the provided code and run.
3. Get the error

**Expected behavior**
Should have get some values (tweets)
**Screenshots**
![image](https://user-images.githubusercontent.com/4152843/120937250-85822080-c6da-11eb-8ac5-c1177d349774.png)

**Comment by JosiahParry** [comment]
This means that you do not have access to the resource. 403 is forbidden access. Either your access token is empty or you do not have permission to access the data. This is not a problem with the source code.

**Comment by justinchuntingho** [comment]
Just for clarify, are you using a bearer token from academic product track (not the one when you create an app)?

**Comment by ombudsmanviktor** [comment]
I've got the same error here. Using a bearer token from academic product track. Already tried to regenerate the bearer and all the tokens/secrets, but nothing worked. Any tips?

**Comment by lingling1123** [comment]
@justinchuntingho 

Hey, 
I've got the same error as you. did you fix it?? 
Thanks in advance
